sources:
  - name: "Go Modules"
    ecosystem: "golang"
    packages:
      - id: "pkg:golang/golang.org/x/mod@v0.31.0"
        name: "golang.org/x/mod"
        purl: "pkg:golang/golang.org/x/mod@v0.31.0"
        version: "v0.31.0"
      - id: "pkg:golang/gopkg.in/yaml.v3@v3.0.1"
        name: "gopkg.in/yaml.v3"
        purl: "pkg:golang/gopkg.in/yaml.v3@v3.0.1"
        version: "v3.0.1"
        
  - name: "NPM Modules"
    ecosystem: "npm"
    packages:
      - id: "pkg:npm/lodash@4.17.20"
        name: "lodash"
        purl: "pkg:npm/lodash@4.17.20"
        version: "4.17.20"
      - id: "pkg:npm/express@4.17.1"
        name: "express"
        purl: "pkg:npm/express@4.17.1"
        version: "4.17.1"
